Fix panic when the Provider spec is empty in credential request
openshift/cloud-credential-operator pull request #484
Opened 2022-08-10 08:44 UTC by Karthik-K-N

This PR contains the changes to fix the panic while generating a secret from a credential request when the Provider spec is empty or wrongly indented, Instead of panic the below error is thrown

```
2022/08/10 14:11:35 Failed to validate the serviceID: Spec.ProviderSpec is empty in powervs-block-csi-driver-operator credentials request
```

2022-08-10 09:43 UTC, Karthik-K-N commented
/cc @mkumatag

2022-08-10 13:27 UTC, mkumatag requested changes
LGTM, can you please add some UT around this scenarios?

2022-08-10 14:52 UTC, 2uasimojo commented
/assign @akhil-rane

2022-08-10 17:13 UTC, akhil-rane reviewed
/lgtm

2022-08-11 06:53 UTC, Karthik-K-N commented
/bugzilla refresh

2022-08-11 06:57 UTC, merged